services:
  - type: pserv
    name: pgAdmin
    runtime: docker
    plan: starter
    disk:
      name: data
      mountPath: /var/lib/pgadmin
      sizeGB: 1
    envVars:
      - key: PGADMIN_LISTEN_ADDRESS
        value: 0.0.0.0
      - key: PGADMIN_DISABLE_POSTFIX
        value: true
      - key: PGADMIN_DEFAULT_EMAIL
        sync: false
      - key: PGADMIN_DEFAULT_PASSWORD
        sync: false